// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgkPEqiL1xp1MMzgkpzEo-VeAJDjG50qk',
    appId: '1:490742211308:web:fb44d07e42ac85ffe43bc9',
    messagingSenderId: '490742211308',
    projectId: 'wisper-74d39',
    authDomain: 'wisper-74d39.firebaseapp.com',
    storageBucket: 'wisper-74d39.firebasestorage.app',
    measurementId: 'G-VSKRQYTX85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxNZ0TrKbOx4GANA7xD396XcqpSFJoVDw',
    appId: '1:490742211308:android:01bc1cc1348b3dc7e43bc9',
    messagingSenderId: '490742211308',
    projectId: 'wisper-74d39',
    storageBucket: 'wisper-74d39.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgkPEqiL1xp1MMzgkpzEo-VeAJDjG50qk',
    appId: '1:490742211308:web:f370e1d01473a331e43bc9',
    messagingSenderId: '490742211308',
    projectId: 'wisper-74d39',
    authDomain: 'wisper-74d39.firebaseapp.com',
    storageBucket: 'wisper-74d39.firebasestorage.app',
    measurementId: 'G-T08D5BY1M1',
  );
}
