// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCM2f6hoq-NhBpV3taZ7JVpiAFq744OPk',
    appId: '1:667291069508:web:e2e31ff4e7d600296ce011',
    messagingSenderId: '667291069508',
    projectId: 'wisper-9f2ab',
    authDomain: 'wisper-9f2ab.firebaseapp.com',
    storageBucket: 'wisper-9f2ab.firebasestorage.app',
    measurementId: 'G-GG6W7RF8V0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx3M0QY83BaEtLmSfyaFYAeV_king70Bc',
    appId: '1:667291069508:android:273d05d9473148596ce011',
    messagingSenderId: '667291069508',
    projectId: 'wisper-9f2ab',
    storageBucket: 'wisper-9f2ab.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCM2f6hoq-NhBpV3taZ7JVpiAFq744OPk',
    appId: '1:667291069508:web:5b70019c537537096ce011',
    messagingSenderId: '667291069508',
    projectId: 'wisper-9f2ab',
    authDomain: 'wisper-9f2ab.firebaseapp.com',
    storageBucket: 'wisper-9f2ab.firebasestorage.app',
    measurementId: 'G-02Z30YV0M0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuFfTzsfs_EQtwCQRAoRNbgPO8WXxrKfw',
    appId: '1:667291069508:ios:7dd105f3322a77da6ce011',
    messagingSenderId: '667291069508',
    projectId: 'wisper-9f2ab',
    storageBucket: 'wisper-9f2ab.firebasestorage.app',
    iosBundleId: 'com.example.wisper',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuFfTzsfs_EQtwCQRAoRNbgPO8WXxrKfw',
    appId: '1:667291069508:ios:bfa161b2712e65d06ce011',
    messagingSenderId: '667291069508',
    projectId: 'wisper-9f2ab',
    storageBucket: 'wisper-9f2ab.firebasestorage.app',
    iosBundleId: 'com.wisperuser.app',
  );

}